[[plugin]]
id = "unquenchedservant/dhvtimer"
name = "DHV Timer"
version = "2.0.1"
min_noctalia = "5.0.0"
author = "chillhumanoid"
tags = ["timer", "productivity"]

[[plugin]]
id = "unquenchedservant/lyrics"
name = "Lyrics"
version = "1.0.3"
min_noctalia = "5.0.0"
author = "chillhumanoid"
tags = ["media", "lyrics"]